#! /usr/bin/env bash

# GNU Mes --- Maxwell Equations of Software
# Copyright ?? 2018 Jan (janneke) Nieuwenhuizen <janneke@gnu.org>
#
# This file is part of GNU Mes.
#
# GNU Mes is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
#
# GNU Mes is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU Mes.  If not, see <http://www.gnu.org/licenses/>.

if [ "$V" = 2 ]; then
    set -x
fi

# Variables
bindir=bin
MES_ARENA=20000000
MES_MAX_ARENA=20000000
MES_STACK=6000000
MES=${bindir}/mes
libdir=${prefix}/lib

dir=$(dirname $0)
${SCHEME-$MES} \
     --no-auto-compile\
     -e main\
     -L /usr/local/share/guile/site/2.2\
     -C /usr/local/lib/guile/2.2/site-ccache\
     $dir/mescc.scm -- "$@"
