#! /usr/bin/env bash

# GNU Mes --- Maxwell Equations of Software
# Copyright ?? 2018 Jan (janneke) Nieuwenhuizen <janneke@gnu.org>
#
# This file is part of GNU Mes.
#
# GNU Mes is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
#
# GNU Mes is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU Mes.  If not, see <http://www.gnu.org/licenses/>.

if [ "$V" = 2 ]; then
    set -x
fi

# Variables
bindir=bin

MES=${MES-${bindir}/mes}

prefix=${prefix-.}
export prefix

includedir=${includedir-${prefix/include}}
export includedir

libdir=${libdir-${prefix}/lib}
export libdir

MES_ARENA=${MES_ARENA-20000000}
export MES_ARENA

MES_MAX_ARENA=${MES_MAX_ARENA-${MES_ARENA}}
export MES_MAX_ARENA

MES_STACK=${MES_STACK-6000000}
export MES_STACK

mes_cpu=${mes_cpu-x86}
export mes_cpu

sep=
if [ "$(basename ${SCHEME-$MES})" = "mes" ]; then
    sep=--
fi

dir=$(dirname $0)
${SCHEME-$MES} \
     --no-auto-compile\
     -e main\
     -L /usr/local/share/guile/site/2.2\
     -C /usr/local/lib/guile/2.2/site-ccache\
     $dir/mescc.scm $sep "$@"
